### ISSUE TITLE
404 error following http://scorreia.com/software/panflute/

### ISSUE THREAD

**Issue by ousia** [sergiocorreia/panflute#1]
I’m afraid that following http://scorreia.com/software/panflute/ points to a non-existent resource (I get a 404 error).

**Comment by sergiocorreia** [comment]
Yes, I'm just finishing setting up the sphinx website today, so it should be up and running in a few hours :)

**Comment by sergiocorreia** [comment]
Synced the website; the user guide is still incomplete though
