### ISSUE TITLE
How to replace header text?

### ISSUE THREAD

**Issue by ptmkenny** [sergiocorreia/panflute#102]
I'm trying to use panflute to convert markdown second-level headers (##) to html because Commonmark does not automatically generate the HTML ids I need for internal links.

Based on the documentation example, this is what my code looks like:
 
```
def action(elem, doc):
    if isinstance(elem, Header) and elem.level <= doc.depth:
        item = ListItem(Plain(*elem.content))
        stringitem = stringify(item)
        # Convert 2nd-level header to HTML because commonmark doesn't automatically generate IDs.
        elem.content = Inline(str('<h2 class="') + stringitem + str('">') + stringitem + str('</h2>'))
```

I'm getting an "TypeError: 'Inline' object is not iterable" error. I looked through the filter examples to try to find something similar and found [the uppercase headers example](https://github.com/sergiocorreia/panflute-filters/blob/master/filters/uppercase_headers.py), but this walks through each string separately; what I want to do is to extra the entire header and process it, and then replace the older header with the new header.  How can I do that?

**Comment by daniel-keller** [comment]
`stringify(elem)` will return the raw text of the header.

**Comment by ptmkenny** [comment]
> `stringify(elem)` will return the raw text of the header.

Thanks @daniel-keller!

I updated my code as you suggested, but I'm still getting an "object is not iterable" error.

```
def action(elem, doc):
    if isinstance(elem, Header) and elem.level <= doc.depth:
        stringitem = stringify(item)
        # Convert 2nd-level header to HTML because commonmark doesn't automatically generate IDs.
        elem.content = Inline(str('<h2 class="') + stringitem + str('">') + stringitem + str('</h2>'))
        stringitem = stringify(elem)
        # Convert 2nd-level header to HTML link because commonmark doesn't automatically generate IDs.
        elem.content = RawInline(str('<h2 class="') + stringitem + str('">') + stringitem + str('</h2>'), 'html')
```

I also tried this but I still get an "object is not iterable" message.

```
        elem.content = Header(RawInline('stringitem','html'), level=2, identifier='stringitem')
```

I tried to understand the documentation, which says "Namely, Element.content is not a list attribute but a property accessed via getter and setters."  I don't really understand what this means, but it seems that this is what I'm doing wrong, because I am trying to set the content directly.

**Comment by daniel-keller** [comment]
I think this is what you want. Its been a few months since I've used panflute so I would need to look into it more to figure why the error is being thrown. I remember it was a little frustrating at first b/c the errors are cryptic but once you get the hang of it panflute with pandoc is a great tool.
```
def action(elem, doc):
    if isinstance(elem, Header) and elem.level <= doc.depth:
        stringitem = stringify(elem)
        # Convert 2nd-level header to HTML link because commonmark doesn't automatically generate IDs.
        return RawBlock(str('<h2 class="') + stringitem + str('">') + stringitem + str('</h2>'), 'html')
```
If you only need the header to be in html instead of markdown and you don't need to modify the headers content you can also use `convert_text()`. This makes sub-pandoc directly in your filter. This works well for cases where you need different syntax in different parts of your document (e.g. all the headers need to be html5 while the rest of the document is markdown).

```
def action(elem, doc):
    if isinstance(elem, Header) and elem.level <= doc.depth:
       # converts the panflute element to html
       return RawBlock(convert_text(elem, input_format='panflute', output_format='html'))
```
If you're using convert_text be aware of this issue https://github.com/sergiocorreia/panflute/issues/99 when converting inline elements.

**Comment by ptmkenny** [comment]
@daniel-keller Thanks again, that worked!

Here's the code I'm using now:

```
    if isinstance(elem, pf.Header) and elem.level <= doc.depth:
        stringitem = pf.stringify(elem)
        mynewheader = '<h2 id="' + stringitem + '">' + stringitem + '</h2>'
        return(pf.RawBlock(mynewheader))
```
