### ISSUE TITLE
Filter to add stuff before and after a div element

### ISSUE THREAD

**Issue by ptmkenny** [sergiocorreia/panflute#109]
I'm trying to write a filter with panflute that, when converting from HTML to ConTeXt, adds a startbackground and stopbackground to a div element.

Inside the div (the div content) are several paragraphs of text and an ordered list.  However, my filter currently renders the ordered list as plaintext because I am using `stringify()`.  What can I use instead to pass the content of the div element "as is" and add the start and stop commands before and after the div?

Here's my filter:

```
    import panflute as pf
    
    def action(elem, doc):
        if isinstance(elem, pf.Div) and ('highlighter' in elem.classes) and (doc.format == 'context'):
        highlighterbg = '\starthighlighter' + pf.stringify(elem) + '\stophighlighter'
        return(pf.RawBlock(highlighterbg,'tex'))
    
    def main(doc=None):
        return pf.run_filter(action, doc=doc)

```

**Comment by K4zuki** [comment]
Use `elem.content` which is a list of elements. 

I made similar filter before:
https://github.com/pandocker/tex-landscape/blob/31630ce0777b7b477dd74fb1d122593f52735446/pandocker_tex_landscape/pandocker_tex_landscape.py#L16

Hope this helps

**Comment by ptmkenny** [comment]
Perfect, that's exactly the example that I needed!
