### ISSUE TITLE
Support Pandoc's new JSON API

### ISSUE THREAD

**Issue by sergiocorreia** [sergiocorreia/panflute#11]
Pandoc will introduce several "breaking changes" in its JSON format ([changelog](https://github.com/jgm/pandoc-types/blob/87077241ad2d082adc65b414bf1af860bd9469b8/changelog)).

## Pandoc changes

- Elements with no children (Space, SoftBreak, LineBreak, HorizontalRule, Null) previously had an empty array for their "c" value. We remove that here.

- New toplevel JSON format with api-version. The toplevel format was previously:

        [{"unMeta": META}, [BLOCKS]]

    It is now:

        {
         "pandoc-api-version" : [MAJ, MIN, REV],
         "meta" : META,
         "blocks": BLOCKS
        }

- Add a LineBlock block element

**Comment by wagnerluis1982** [comment]
Good move!

But a question: the idea is to detect automatically the new format or will be required by the programmer to set the version?

**Comment by sergiocorreia** [comment]
Completely automatic; the idea is that the user should not even realize there are multiple APIs.
