### ISSUE TITLE
How to add custom styles from epub to docx

### ISSUE THREAD

**Issue by ptmkenny** [sergiocorreia/panflute#111]
I'm trying to convert an epub to docx.

The epub uses divs to format text, and I want to convert these divs to Word styles.

I made a custom reference.docx according to the documentation (https://pandoc.org/MANUAL.html#custom-styles-in-docx-output).

I added a custom style, **Banana**, to the reference.docx.

Then I wrote a custom filter in panflute:

```
import panflute as pf

def action(elem, doc):
    if isinstance(elem, pf.Div):
        if 'banana' in elem.classes:
            elem.content.insert(0, pf.RawBlock('::: {custom-style="Banana"}', format="markdown"))
            elem.content.append(pf.RawBlock(":::", format="markdown"))
```

Unfortunately, when I run pandoc with the panflute filter, the text in the banana divs is not converted to the Banana style in the docx file.  What else do I need to do to get the conversion to work?

**Comment by K4zuki** [comment]
Try `elem.attribute` to add `{"custome-style": "Banana"}` dictionary.
Following implementation may be helpful for you:
https://github.com/pandocker/pandoc-docx-utils-py/blob/65fa8a8afe312f4c06d28e5a1aebe600e585bd13/pandoc_docx_utils/__init__.py#L18
