### ISSUE TITLE
RawBlock RAW_FOMARTS fail for mediawiki

### ISSUE THREAD

**Issue by lllama** [sergiocorreia/panflute#117]
Related to #67 but when I try and convert the following mediawiki syntax:
```
{{some-feature
|test=case
}}
```
I get a `TypeError` that `str` is not in `RAW_FORMATS`. This is failing on pages where we've implemented custom mediawiki elements.

**Comment by lllama** [comment]
It looks like `mediawiki` is the format being checked, so maybe that could be added to `RAW_FORMATS`

**Comment by lllama** [comment]
Created #118 to add this to the list

**Comment by sergiocorreia** [comment]
Thanks, I added the PR. Also, perhaps it would be better to remove the check altogether, to allow any format (I stead of having to whitelist the allowed ones)
