### ISSUE TITLE
`shutilwhich` listed as requirement for python3

### ISSUE THREAD

**Issue by toddrme2178** [sergiocorreia/panflute#119]
The `shutilwhich` package is needed for python2, but not python3 which has it built-in.  However, it is listed as a requirement even for python3, which means it will get pulled in for no reason.  

We have this package in openSUSE, and this dependency causes a problem because we don't have a python3 version of `shutilwhich` (there is no point).  But packages that depend on `panflute` end up failing because `panflute` incorrectly says it needs `shutilwhich` for python3.

**Comment by sergiocorreia** [comment]
I agree. I was planning on dropping py2 support around the time the clock [expires](https://pythonclock.org/) but I can also do it sooner if it's useful on your side (don't think many people will mind).

**Comment by toddrme2178** [comment]
I have a workaround for now.  It is up to you.
