### ISSUE TITLE
Quotes Are Dropped When Stringifing Enclosing Paragraph

### ISSUE THREAD

**Issue by OptikSage** [sergiocorreia/panflute#129]
The follow code:

import panflute as pf

text = "Some quoted text"
quoted_text = pf.Quoted(pf.Str(text))
para_with_quoted_text = pf.Para(quoted_text)
pf.debug(pf.stringify(para_with_quoted_text, False))

results in _Some quoted text_
but should be _"Some quoted text"_

**Comment by sergiocorreia** [comment]
In general, `stringify()` does it's job but is not very powerful (the [code](https://github.com/sergiocorreia/panflute/blob/master/panflute/tools.py#L183) is only a few lines).

I added the quotes so it should work as you expected, but be aware that it might not be powerful when dealing with other text elements (for instance, if you have citations, footnotes, etc.).
