### ISSUE TITLE
pandlute.Doc or panflute.elements.Doc

### ISSUE THREAD

**Issue by NMarkgraf** [sergiocorreia/panflute#131]
Hi all!

Got this error message today:

> File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/panflute/io.py", line 127, in dump
>    assert type(doc) == Doc, "panflute.dump needs input of type panflute.Doc"
> AssertionError: panflute.dump needs input of type panflute.Doc

`doc` is of type `panflute.elements.Doc` not `panflute.Doc`. What is the difference between that two class types and how to fix the problem?

Cheers
Norman

**Comment by sergiocorreia** [comment]
How did you got that error?

Also, although Doc is defined I elements, I believe that exposing it in __init__ makes of class panflute.Doc (but would have to double check)

**Comment by NMarkgraf** [comment]
Hi Sergio!

Thanks in advance!

I wrote a short filter that removes header blocks depending on some header attributes. If the header block is the last in the markdown file and it is removed by the filter this error occurs.

What I found out in short is:
 
```
import panflute as pf
[...]
instance(doc, pf.Doc)  # True
type(doc)  # <class 'panflute.elements.Doc'>
```

Maybe you should simply change the line 

```
assert type(doc) == Doc, "panflute.dump needs input of type panflute.Doc"
```

in `io.py` to something like

```
assert isinstance(doc) == Doc, "panflute.dump needs input of type panflute.(elements).Doc"
``

I'm not sure. 

But this error is reproducible .

Cheers,
Norman

**Comment by NMarkgraf** [comment]
Hi Sergio,

I tried to make a simple version of the problem. Please look at the code in the Archiv.zip.

Running it like this
```
pandoc -i "Maybe an error.md" -o "Maybe an error.pdf" -t beamer -s --filter=tinyremover.py
```

will produce the following error message:

```
Traceback (most recent call last):
  File "./../tinyremover.py", line 52, in <module>
    main()
  File "./../tinyremover.py", line 43, in main
    ret = pf.run_filter(action, doc=doc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/panflute/io.py", line 260, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/panflute/io.py", line 247, in run_filters
    dump(doc, output_stream=output_stream)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/panflute/io.py", line 127, in dump
    assert type(doc) == Doc, "panflute.dump needs input of type panflute.Doc"
AssertionError: panflute.dump needs input of type panflute.Doc
Error running filter ../tinyremover.py:
Filter returned error status 1
```

[Archiv.zip](https://github.com/sergiocorreia/panflute/files/4121252/Archiv.zip)

**Comment by NMarkgraf** [comment]
...

**Comment by NMarkgraf** [comment]
found it. - thanks.

**Comment by sergiocorreia** [comment]
Hi Norman,

Sorry for the delayed reply; free time is scarce lately. I'm assuming you already found the problem, which *I think* lies on the last element of the iteration (the `Doc`) being deleted via  `return []`?

In any case, I'm adding commit that should make these issues a bit easier to spot (it's already hard enough to know when something doesn't work).

Best,
Sergio

**Comment by NMarkgraf** [comment]
Hi Sergio,

exactly. If you look-ahead you should take care that it is possible to be the last one. ;-) I hacked panflute a little bit to find that out. It would be much easier not to say that `Doc` is expected, but also what is  actual there, that raises the error. ;-)
After I saw that, I found the error in under 30 sec.  But a little bit more information in case of an error would be a great idea! 

Regards,
Norman
