### ISSUE TITLE
Syntax error 'oktypes'

### ISSUE THREAD

**Issue by TheGroundZero** [sergiocorreia/panflute#136]
Hi

I'm trying to write a simple filter that replaces Hugo `figure` shortcodes with Markdown image code (and changes the path to the local path).

However, running pandoc using this filter, I get the following error.

```bash
Traceback (most recent call last):
  File "./pandoc_unfigure.py", line 2, in <module>
    import panflute as pf
  File "/home/.../.local/lib/python2.7/site-packages/panflute/__init__.py", line 9, in <module>
    from .containers import ListContainer, DictContainer
  File "/home/.../.local/lib/python2.7/site-packages/panflute/containers.py", line 42
    def __init__(self, *args, oktypes=object, parent=None):
                                    ^
SyntaxError: invalid syntax
Error running filter ./pandoc_unfigure.py:
Filter returned error status 1
```

```bash
$pandoc --version
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2
Default user data directory: /home/.../.local/share/pandoc or /home/.../.pandoc
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

It doesn't look like this error is related to my actual script.

I've tested both the regular pip as the Git pip version of panflute.

Just to be sure, I'm including my filter script below

```python
#!/usr/bin/env python3
import panflute as pf
import re
import sys


"""
Pandoc filter that modifies Hugo {{figure}} shortcode
to be replaced with actual images.
"""


def unfigure(elem, doc):
    if isinstance(elem, pf.Para):
        source = pf.stringify(elem, newlines=False)
        sys.stderr.write(source + "\n")
        res = re.sub('\s*{{< figure src="(.*?)".*alt="(.*?)".*caption="(.*?)".*>}}', r'![\2](/home/.../static\1 "\3")', source)
        sys.stderr.write(res)
        new_elem = pf.convert_text(res)
        return elem


def main(doc=None):
    return run_filter(unfigure, doc=doc)

if __name__ == "__main__":
    main()
```

This should replace  
`{{< figure src="/img/htb-networked-img1.png" alt="Screenshot of upload.php" position="center" caption="upload.php" captionPosition="center" >}}`  
with  
`[Screenshot of upload.php](/home/.../static/img/htb-networked-img1.png "upload.php")`

**Comment by ickc** [comment]
Hi, we need more info. You already provided the script, and some input and output. Why don't you also write down the exact command you used? Also, try to provide both the Python version (run `python --version`) and panflute version (something like `panflute.__version__` after importing it in Python.)

**Comment by sergiocorreia** [comment]
From the debug output, it seems this is in py2.7. Will close for now unless we find a MWE where the bug happens in py3.
