### ISSUE TITLE
Wrapping code block with docx custom style without losing syntax highlighting 

### ISSUE THREAD

**Issue by SuperV1234** [sergiocorreia/panflute#138]
Hello, I am trying to write a filter to find all code blocks and wrap them into a custom `.docx` style. This is what I tried:

```python
if type(elem) == pf.CodeBlock:
        return pf.Div(elem, attributes={'custom-style': 'Source Code Boxed'})
```

However, that doesn't work - it seems that the syntax highlighting styles override my desired `'Source Code Boxed'` style. I found a workaround, but it is ugly, and loses all the syntax highlighting:

```python
if type(elem) == pf.CodeBlock:
    elemStr = pf.stringify(elem)
    lines = [pf.LineItem(pf.Str(x)) for x in elemStr.splitlines()]
    return pf.Div(pf.LineBlock(*lines), 
            attributes={ 'custom-style': 'Source Code Boxed'})
```

The above works (it surrounds my code block in a box in my final `.docx` output), but all syntax highlighting is lost.

**Is there a way to achieve my desired result?** I would the code being surrounded in a box (thanks to my `'Source Code Boxed'` style), but still retain its syntax highlighting.

**Comment by ickc** [comment]
Actually this is not a filter question. It is more like a pandoc question as you can write down the markdown syntax corresponding to what you're trying to achieve. (Ie a div with attributes then a code block, and markdown with this content convert to docx.)

I think you'd have better luck trying to ask this in pandoc discuss first, trying to find a markdown input that would produce your desired docx output. After that, you can start thinking how to write a filter that does that automatically.

Closing as this is more of a pandoc question.

**Comment by ickc** [comment]
Also, have you tried adding the attributes directly to the code block, not creating a doc around it? Code block supports attributes.
