### ISSUE TITLE
Reference to TechnicalMarkdown

### ISSUE THREAD

**Issue by gabyx** [sergiocorreia/panflute#140]
Maybe add a reference to 
https://github.com/gabyx/TechnicalMarkdown

BR

**Comment by ickc** [comment]
No reason or introduction provided. Not enough information to work on. Closing for now.

**Comment by gabyx** [comment]
It uses panflute in its setup.

**Comment by sergiocorreia** [comment]
We can definitely add it to the readme as an example ,but keeping it low-priority until we fix the pandoc 2.10 issue.

**Comment by ickc** [comment]
PR is preferable in this case.
