### ISSUE TITLE
replace_keyword skips over cites

### ISSUE THREAD

**Issue by holmescharles** [sergiocorreia/panflute#141]
I want to replace keywords everywhere they occur. See my example:

```markdown
# This is the heading {#sec:alpha}

This is ref 1 = @sec:alpha

This is ref 2 = {@sec:alpha}

This is ref 3 = [@sec:alpha]

This is ref 4 = [{@sec:alpha}]

```

Then I run 'pandoc test.md -o test.pdf --filter ../filters/headxref.py'. In brief, this finds all those tags, associates them with the header title, and runs "replace_keyword" on the document, replacing, e.g., "@sec:alpha", with "This is the heading".

This yields the following in the output:

<img width="326" alt="image" src="https://user-images.githubusercontent.com/1988783/83782018-e785f100-a654-11ea-898f-260c4d6f6339.png">

So why is it skipping Cite blocks?

**Comment by sergiocorreia** [comment]
With `.replace_keyword()`, Panflute walks over all elements and replaces the `Str()` elements where `.text` **exactly matches** your input. This means that:

1. If you have a text "abcde", then replacing "bcd" will not change anythng.
2. Other attributes of the element are not replaced (such as the `url` attribute of `Link()` objects, or in your case, the `.id` attribute of `Citation()`.

For instance, in ref1, `@sec:alpha` is interpreted by pandoc as a citation object:

```haskell
[Cite
    [Citation
        {citationId = "sec:alpha",
        citationPrefix = [],
        citationSuffix = [],
        citationMode = AuthorInText,
        citationNoteNum = 1,
        citationHash = 0}]
    [Str "@sec:alpha"]
]
```

And the filter modifies the contents of the `Str` object (but not the citationId!)

Now, in ref4:

```haskell
Cite
    [Citation
        {citationId = "sec:alpha",
         citationPrefix = [Str "{"], citationSuffix = [Str "}"],
        citationMode = NormalCitation,
        citationNoteNum = 1,
        citationHash = 0}]
    [Str "[{@sec:alpha}]"]
]
```

You see that the Str object is actually equal to "[{@sec:alpha}]", so nothing changes.

Extending the replace_keyword() function to match substrings is not that difficult though, and it would involve changing just two lines:

**Comment by holmescharles** [comment]
Follow up question: It seems that replacing the Str text would still leave the citation object, which would be seen by a crossref or citation filter, e.g., citeproc or crossref. Is there a trivial way to replace the whole citation with a Str?

**Comment by sergiocorreia** [comment]
Not with `.replace_keyword()`, but you can set up a filter that looks for `Cite` elements and then replaces the element as needed if its contents match the keyword. A bit more cumbersome of course.

Longer term, it might be useful to have a more powerful replace_keyword, if there is enough demand for it.
