### ISSUE TITLE
Minimal git flow

### ISSUE THREAD

**Issue by ickc** [sergiocorreia/panflute#150]
As I'm helping with merging PR, I'm going to create a minimal git flow.

- master: I won't touch this
- stable: I'll merge PRs into this. This represents a stable version that tests are passing for pandoc 2.7-2.9 for now. Any new pull requests that doesn't break panflute tests for pandoc 2.9 will be merged to here.
- develop: I'll merge PRs into this. This will breaks pandoc 2.9 support and eventually should support pandoc 2.11. Nothing committed to here yet as of writing.

**Comment by ickc** [comment]
To @sergiocorreia, don't worry with this git flow. My thinking is that when there's a new version for panflute, I'll create PR from these 2 branches so that you can review them in batch.

**Comment by ickc** [comment]
As develop is now passing tests for pandoc 2.11, the git flow (which was a stop gap measure to handle failing CIs) is no longer needed. The develop could be kept if needed, stable branch will be deleted.

**Comment by sergiocorreia** [comment]
Let's delete both branches, as we can always create them again if needed
