### ISSUE TITLE
Regression: panflute.elements.builtin2meta no longer supports subclasses of builtins

### ISSUE THREAD

**Issue by dhimmel** [sergiocorreia/panflute#166]
https://github.com/sergiocorreia/panflute/commit/a72ffb5b48ca2c871ad8818595cf0ae888c91f4c was first released in 2.0.3. It breaks support for converting subclasses of builtin types to pandoc meta types. This is because it stops using `isinstance` and directly compares type instead. CC @ickc 

This caused the issue mentioned at https://github.com/manubot/rootstock/pull/386#issuecomment-724926969 and https://github.com/sergiocorreia/panflute/issues/164#issuecomment-724938868:

```python-traceback
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/panflute/containers.py", line 76, in insert
    v = check_type(v, self.oktypes)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/panflute/utils.py", line 71, in check_type
    raise TypeError(msg)
TypeError: 

Element "MetaList" received "CSL_Item" but expected <class 'panflute.base.MetaValue'>
```

CSL_Item is a dict subclass.

**Comment by ickc** [comment]
Thanks. Can you give me a MWE here?

**Comment by dhimmel** [comment]
> Can you give me a MWE here?

```python
class My_Dict(dict):
    pass

my_dict = My_Dict()
data = [my_dict]
pf.elements.builtin2meta(data)
```
Raises
```
TypeError: 
Element "MetaList" received "My_Dict" but expected <class 'panflute.base.MetaValue'>
```

**Comment by ickc** [comment]
Thanks. I'm looking at it right now. In real cases would the only subclasses used be of Block and Inline? Or any of the types?

If it is only Block and Inline, then we can special case them. Else, just revert that commit.

**Comment by dhimmel** [comment]
What about my suggestion at https://github.com/sergiocorreia/panflute/pull/146#issuecomment-725713536

> Perhaps if this speed increase is substantial, you could try your type lookup first, and if no match fallback to isinstance.

I will submit a PR

> In real cases would the only subclasses used be of Block and Inline?

I think any builtin types might be subclassed

**Comment by sergiocorreia** [comment]
Ok, I finally understand the issue a bit better. Was initially confused about it being related to `_res_func` but it's just about `builtin2meta`

**Comment by ickc** [comment]
Right, see comment at https://github.com/sergiocorreia/panflute/pull/167#issuecomment-725722270
