### ISSUE TITLE
Exception: unknown tag: ColWidthDefault

### ISSUE THREAD

**Issue by guptachetan1997** [sergiocorreia/panflute#182]
Getting the exception when markdown file is using tables in version 2.0.5 of panflute. Pandoc version is 2.11.3.2

**Comment by ickc** [comment]
Can you provide a minimal working example?

Include the markdown file, command used in addition to the versions you provided. And also which platform (OS + arch, by e.g. `uname -a`.)

**Comment by ickc** [comment]
Closing as it is very likely an environment setup problem.

Reopen if MWE is provided. Including the environment for example

```bash
which python
python --version
python -c 'import panflute; print(panflute.__version__)
which pandoc
pandoc --version
uname -a
...
```

and the markdown input, command used to run pandoc with panflute, etc.

**Comment by bkasel** [comment]
Hello, I encountered the same error. I narrowed it down to  a table in markdown
```{python}
    txt = """
Height (m)   Time (sec)
------------ ------------
0.490        0.1
0.882        0.2
1.176        0.3
1.372        0.4
1.470        0.5
1.470        0.6
1.372        0.7
"""

pf.convert_text(txt, input_format="markdown")

```

using panflute 2.0.5 on python 3.9 on windows and pandoc 2.11

**Comment by bkasel** [comment]
I stumbled on the same problem, when using tables in markdown. As suggested I tracked the problem down to an imcompatibility between pandoc 2.11 and an outdated panflute version 1.x 
The problem came from a confusion between using vanilla python and Anaconda side by side. Jupyter notebook started in Anaconda while python started the vanilla interpreter.

Thank you!

**Comment by ickc** [comment]
My recommended way to install the stack is

```bash
# replace conda by mamba if you have that
conda install pandoc panflute ... -c conda-forge
```

The run_constraint of panflute (and pantable) will enforce a matching version of pandoc if you install this way.
Also, installing pandoc via conda guarantees you the jupyter environment is calling the right one (jupyter doesn't know your PATH, so it can call a different pandoc than you set up in your shell.)

Among other pandoc filters, at least pandoc-crossref is also available in conda. My plan is for any pandoc filters I personally need, I'll create a conda recipe for that.
