### ISSUE TITLE
Publish panflute 2.1.0 to zenodo

### ISSUE THREAD

**Issue by ickc** [sergiocorreia/panflute#184]
We could do something similar to pandoc in https://zenodo.org/record/4625265 , which makes this software citable code.

registering seems easy, you can log in using GitHub account and then flip a switch for panflute repo. After next release then there’s one more step to do, and any future releases should be automatic.

@sergiocorreia, interested?

**Comment by sergiocorreia** [comment]
Definitely!

**Comment by ickc** [comment]
Thanks for merging #177.

Next steps:

1. Push panflute 2.1.0 to PyPI. (version string is already 2.1.0)
2. Go to https://zenodo.org/account/settings/github/ , "Log in with GitHub".
3. In https://zenodo.org/account/settings/github/ , toggle the switch of panflute.
4. Tag it in GitHub Releases, with a standard title like "Panflute 2.1.0" (this will be the Zenodo release title.)
5. It should be live on Zenodo automatically after the GitHub Releases is tagged.

**Comment by sergiocorreia** [comment]
Hi Kolen,

I created a release in order to push it with pypi (it's done automatically via github actions). However, the action failed:

https://github.com/sergiocorreia/panflute/runs/2349746072?check_suite_focus=true

```
Run python3 setup.py sdist bdist_wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
Error: Process completed with exit code 1.
```
Do you have any idea about what might be the problem? I suspect we might be missing the `wheel` package (see [here](https://github.com/sergiocorreia/panflute/blob/master/.github/workflows/publish.yml) and [here](https://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci)).

Is it just a matter of changing this line?

https://github.com/sergiocorreia/panflute/blob/master/setup.py#L112

**Comment by ickc** [comment]
Probably it is just missing the dep wheel, see #184.

(CI is easy to break as it can't be tested locally...)
This time I tested it with a virtual environment and followed the commands of `publish.yml` and it works. So probably the CI would now work too.

**Comment by ickc** [comment]
By the way, the GitHub Releases should be before setting up Zenodo in https://zenodo.org/account/settings/github/ as that also trigger a release in Zenodo.

**Comment by frederik-elwert** [comment]
I just noticed that panflute 2.1 is not yet on PyPI. Since that’s also mentioned here, I thought before creating another issue I’d just ask here if anything is blocking the PyPI release?

**Comment by ickc** [comment]
The owner is probably having family emergency and is not responsive on GitHub right now. So let’s give him some time there.

I have the conda forge admin right but not the PyPI’s. Would conda help?

**Comment by frederik-elwert** [comment]
Thank you! In my case conda would not help, but then I'll take the github version, no worries!

**Comment by ickc** [comment]
I upgraded the conda-forge package anyway: https://anaconda.org/conda-forge/panflute/files

**Comment by sergiocorreia** [comment]
BTW, I finally did the pypi and zenodo tasks. PyPI is now live, but zenodo seems to take quite a bit to build the tarball and create the DOI:

![image](https://user-images.githubusercontent.com/214056/120055447-22222f80-c004-11eb-9ad0-813c08f90295.png)
