### ISSUE TITLE
Is there an updated documentation?

### ISSUE THREAD

**Issue by me-kell** [sergiocorreia/panflute#197]
The documentation under http://scorreia.com/software/panflute/ seems not up to date. It doesn't mention e.g. the class `TableBody`

**Comment by ickc** [comment]
Yes, Meanwhile I have an up-to-date documentation at https://panflute.readthedocs.io/en/latest/

**Comment by ickc** [comment]
See #180. Closing as duplicated.

**Comment by me-kell** [comment]
Thanks for your answer.

May I suggest to add the panflute version to the documentation?
If possible in a prominent place in the text?
And, also if possible, referring to other documentation's versions and compatibility problems. E.g. the "Note on versions" on github. That way the documentation would be copletely in one place (instead of splited in github and readthedocs).

The html-title of the documentation's landing page says "Panflute: pandoc filters made simple — panflute 2.1.0 documentation". But this is not really visible on the browser's tab.

IMHO the LaTeX ecosystem is often not so easy when it comes to set a complex environment with compatible versions of different packages, engines, distributions etc.

**Comment by sergiocorreia** [comment]
This is due to two problems:

1. `sphinx` was not running correctly, as I was using `make html` which in case of error failed silently (no idea why)
2. `git` at some point stopped following symlinks on windows, so changes were not being propagated from the panflute repo to my website repo. Will see if there's an alternative, else I'll just copy-paste every time I build.

**Comment by sergiocorreia** [comment]
Just pushed a commit (and website update) that should fix this, including the missing class docstrings. Please reopen if it's not the case.

**Comment by ickc** [comment]
It will be easier to continue the discussion in #180 for discovery.

panflute.readthedocs.io has been versioned, part of the benefits of using readthedocs where this comes for free.
