### ISSUE TITLE
Allow action function to return list of elements?

### ISSUE THREAD

**Issue by jacobwhall** [sergiocorreia/panflute#199]
A [note in the documentation](http://scorreia.com/software/panflute/code.html#panflute.io.toJSONFilters) makes clear the "rules of action functions:"

> - They can return either an element, None, or [].
> - If they return None, the document will keep the same document as before (although it might have been modified).
> - If they return another element, it will take the place of the received element.
> - If they return [] (an empty list), they will be deleted from the document. Note that you can delete a row from a table or an item from a list, but you cannot delete the caption from a table (you can make it empty though).

The filter I am working on requires replacing elements _with multiple elements_. It would be convenient to write an action function that returns a list of elements, that are then written over the element in question. This is currently difficult to accomplish from within an action function. If you are open to this change, I would be happy to submit a PR.

Thanks!

**Comment by ickc** [comment]
I think this behavior is started from the pandocfilters.

Replacing the element is simple, but if you want to replace it with multiple elements, it depends on the context (e.g. if the current element is in a list container, you then need to expand this list.

Did you already have an idea how this proposed feature can be implemented while keeping the simplicity? If not, I'm afraid this is making it too complicated.

For people who really need to replace a single element by multiple ones, they can either replace it with a Div that encloses those multiple elements, or if they really need to expand the list, they can access the parent and modify from there (which is not pretty, but doable within the current framework.)

**Comment by sergiocorreia** [comment]
I quite like this request, as it's something that I've wanted to use in the past while writing my own filters. That said, I'm a bit time constrained, so for the next ~2 weeks (at least) won't be able to implement it, but will definitely look at PRs

**Comment by ickc** [comment]
Note that as we open this up for change, a signature that makes more sense would be that the action has the following signature:

```python
from typing import Optional
import panflute as pf

def action(
    element: Optional[pf.Element],
    doc: Optional[pf.Doc],
    **kwargs,
) -> Optional[list[pf.Element]]:
    pass
```

Where

- returning `None` (the sentinel) would do nothing, and else list of elements would be put in-place of the original element.

- returning empty list behavior is the same as before (replacing nothing in-place i.e. delete).

- returning list of single element is the same as the current behavior of returning an element

And for backward compatibility, the actual signature should be

```python
from typing import Optional
import panflute as pf

def action(
    element: Optional[pf.Element],
    doc: Optional[pf.Doc],
    **kwargs,
) -> list[pf.Element] | None | pf.Element:
    pass
```

And I'm not sure if we should ever drop that compatibility.

Type-wise this makes more sense.

**Comment by jacobwhall** [comment]
Today I [began writing tests](https://github.com/jacobwhall/panflute/blob/75b45c5858f5e8313197c2eb294d77ec421303ba/tests/test_walk.py) for this feature, and happily discovered that `Element.walk()` already behaves how I'd like it to for inline and block elements, replacing a given element with a list of returned elements. The lists must only include either inline or block elements, matching the type of the element they are replacing. For many element types, this feature might just be a documentation change.

I am motivated to make this feature happen, and working to better understand panflute in order to do so. For example, I'm not sure if/how lists of MetaValue elements should be supported.

**Comment by sergiocorreia** [comment]
> happily discovered that `Element.walk()` already behaves how I'd like it to for inline and block elements

Yes, it seems that it was added by c0284a468 but we never documented it so I forgot ¯\_(ツ)_/¯

Will add the PR now.
