### ISSUE TITLE
Add comparison method to Element class?

### ISSUE THREAD

**Issue by jacobwhall** [sergiocorreia/panflute#214]
I have been writing tests for a panflute filter, and thinking about how to best validate its output. While the "batteries included" functions like `convert_text()` are helpful for this task, I would like to directly compare elements. I suggest that we add a [`__eq__()` comparison method](https://docs.python.org/3/reference/datamodel.html#object.__eq__) to the `pf.Element` class that verifies that they are identical both in type and in terms of their parameters.

For example, comparing two `pf.Doc` elements would check that both have identical block sequences, metadata, format, and API version.
```python
assert pf.Doc == pf.Doc # succeeds only if all parameters are identical
```
Thank you for your consideration!

**Comment by sergiocorreia** [comment]
Just added this method. I also added a test suite, but haven't tested for correctness as much as I would have liked. So if you spot anything off definitely let me know!

**Comment by jacobwhall** [comment]
Thank you very much!
