### ISSUE TITLE
Travis deploy to PyPI; git tag to GitHub Release

### ISSUE THREAD

**Issue by ickc** [sergiocorreia/panflute#22]
Do you want me to make a pull request such that Travis can help you to release to PyPI automatically?

If travis is setup this way:

- you need to add your password in travis-ci.org as an environmental variable, say, `pypi_password`. (this will not be shown to the public unless you activate "Display value in build log")

- (there are multiple ways to set this up. One way is to use git tag, which has the added bonus to have it "properly" released on GitHub release simultaneously.) You need to use `git tag -a v$(python setup.py --version) -m 'Deploy to PyPI' && git push origin v$(python setup.py --version)` when you release a version.

**Comment by sergiocorreia** [comment]
That would be quite useful! Its easy to forget to push to PyPI

**Comment by ickc** [comment]
Do you use Windows or Unix? Would using `git tag -a v$(python setup.py --version) -m 'Deploy to PyPI' && git push origin v$(python setup.py --version)` (or something similar on Windows) be too troublesome?

Alternatively, we can ask travis to deploy to PyPI every time. Unless the version is boosted, this will resulted in an error (which should be ok in the deploy stage). This way, the only thing you need to do is increment the version and commit.

**Comment by sergiocorreia** [comment]
`$()` expressions don't work with Windows' `cmd`, but it seems they work with `PowerShell` so I can use that.

**Comment by sergiocorreia** [comment]
I just realized that a large part of my workflow involves Github Desktop for Windows, which makes custom git commands harder (I'll search for a way to customize it though)

**Comment by ickc** [comment]
I've made a pull request in #24. Basically forget about GitHub Release, and the use of git command. I setup Travis to deploy to PyPI *everytime* but only when the version bumped it will go through. Effectively you have automatic PyPI deploy every time you make commit on master branch with a bump in version.
