### ISSUE TITLE
panflute.yaml_filter: error handling when YAML is invalid

### ISSUE THREAD

**Issue by ickc** [sergiocorreia/panflute#23]
I'm writing a test on invalid YAML:

    ``` {.table}
    ---
    caption: *unquoted*
    ...
    1,2
    3,4
    ```

which would gives this error:

```bash
yaml.scanner.ScannerError: while scanning an alias
  in "<unicode string>", line 1, column 10:
    caption: *unquoted*
             ^
expected alphabetic or numeric character, but found '*'
  in "<unicode string>", line 1, column 19:
    caption: *unquoted*
                      ^
```

I'm thinking how to handle the error. May be an option can be given to panflute.yaml_filter such that it will do nothing (leave the code block as is) rather than raising an error?

**Comment by sergiocorreia** [comment]
I agree that Python errors should not be allowed to occur.

We could just wrap the YAML reader in a `try ... except` code, and if it fails, then do nothing but issue a warning message?

**Comment by ickc** [comment]
In addition to a warning message in command-line, how about it returns the `options` with only 1 key, say, `{'yaml-error': True}`, so that individual filters can decide how to deal with it? (e.g. One can continue to work with the `data` while ignoring the `options` with "sensible defaults".)

By the way, I tested invalid YAML in pandoc and it will do:

```bash
$ printf "%s\n" '---' 'title: *unquoted*' '---' '' 'non-empty' | pandoc -f markdown -t native --css=abc.css
pandoc: Could not parse YAML header: did not find expected alphabetic or numeric character "source" (line 3, column 17)
Pandoc (Meta {unMeta = fromList []})
[Para [Str "non-empty"]]
```

**Comment by sergiocorreia** [comment]
I wrote the code for the soft error handling, but I think that at least for now the better alternative is not to run the filter at all:

- It would allow the reader of the output to inspect what went wrong (you can just read the code block)
- The errors would be harder to spot (e.g. a table might have the wrong title, instead of just appearing as a code block)

**Comment by ickc** [comment]
I finished my filter in [ickc/pantable: CSV Tables in Markdown: Pandoc Filter for CSV Tables](https://github.com/ickc/pantable). It's based on your csv example but eventually breaks compatibility with it.

One potential problem is exactly what you said above: I handle away all errors in the YAML metadata and override them with "sensible defaults".
