### ISSUE TITLE
Can panflute support match-case? 

### ISSUE THREAD

**Issue by Zhaopudark** [sergiocorreia/panflute#238]
Thanks for this great project! 😄 
I'm working on a Python module, [pandoc-filter](https://github.com/Zhaopudark/pandoc-filter) that based on this project. And I find it will be convenient if panflute can support the [match-case mechanism](https://peps.python.org/pep-0636/) better.

The basic match-case mechanism is as:

```python
content = ['1','2','3']
match content:
    case [str('1'),*_]:
        print("match ok")
    case _:
        print("match failed")
        
class MyStr:
    def __init__(self, text):
        self.text = text
content = [MyStr('1'),MyStr('2'),MyStr('3')]

match content:
    case [MyStr,*_]:
        print("match ok")
    case _:
        print("match failed")
```
And, I want it to work on panflute classes. The expected syntax is as:
```python
import panflute as pf  
content = [pf.Str('1'),pf.Str('2'),pf.Str('3')]

match content:
    case [pf.Str,*_]:
        print("match ok")
    case _:
        print("match failed")
# Expect match ok
```
The above codes do not work in the current panflute version 2.3.0.

Maybe I do not understand [match-case mechanism](https://peps.python.org/pep-0636/) well and do not know panflute fully. My  current alternative is
```Python
import panflute as pf  
content = [pf.Str('1'),pf.Space(),pf.Para(pf.Str('2'))]

match content:
    case [pf_str,*_] if isinstance(pf_str,pf.Str):
        print("match ok")
    case _:
        print("match failed")
```

So, I think it will be convenient if panflute can support the [match-case mechanism](https://peps.python.org/pep-0636/) better. 
Thanks in advance. 🌞

**Comment by NMarkgraf** [comment]
I'm sure, you are right! You do not understand the match-case mechanism. ;-)

pf.Str is some kind of type not a variable, so your work around seems to my the only working way. Sorry.

**Comment by Zhaopudark** [comment]
@NMarkgraf  Thanks. I will consider the problem and paradigms more prudently later.

**Comment by Zhaopudark** [comment]
@NMarkgraf Thanks. I will consider the problem and paradigms more prudently later.
