### ISSUE TITLE
Please update to pandoc 3.1.12.2 if possible

### ISSUE THREAD

**Issue by mfhepp** [sergiocorreia/panflute#241]
Dear @sergiocorreia :
Would it be possible to update Panflute to Pandoc 3.1.x? That would be extremely helpful for many users I guess.

If a pull-request helps and if you can describe the required steps, maybe others can take a share of the burden.

Thanks for your great work!

**Comment by mfhepp** [comment]
From a quick look at pandoc-types, only build dependencies have been changed from 1.23 to the most recent 1.23.* release. So I guess updating to Pandoc 3.1. * should not require actual changes to the code, just a test-run and updating the meta-data.

See 

https://github.com/jgm/pandoc-types/commits/master/

**Comment by sergiocorreia** [comment]
Hi Martin,

Just checked pandoc-types and pandoc and it seems there shouldn't be any problem running panflute with the latest version of pandoc.

Let me know if you experience any problem!

-Sergio

**Comment by mfhepp** [comment]
Thanks a lot, Sergio!
