### ISSUE TITLE
autofilter.py: autorun_filters: KeyError: 'main'

### ISSUE THREAD

**Issue by ickc** [sergiocorreia/panflute#35]
In an attempt to add more tests, I setup Travis to run all `.md` through panflute, which will applies necessary filters according to `autofilter.py` and the YAML.

I then encountered `KeyError: 'main'` in [Job #59.2 - ickc/panflute - Travis CI](https://travis-ci.org/ickc/panflute/jobs/183869868#L449-L457), when processing an `.md` file using the filter `include`.

**Comment by sergiocorreia** [comment]
When panflute runs a filter (instead of when pandoc runs it and the filter imports panflute), it needs a `main()` function that acts as a hook.

This was missing in some of the examples (to make them easier to read) but I updated them so hopefully the tests will compile

**Comment by ickc** [comment]
I see. Forgot about that point when I setup the test. Thanks!
