### ISSUE TITLE
Readme.md is missing from the pip package

### ISSUE THREAD

**Issue by fredizzimo** [sergiocorreia/panflute#4]
The readme.md file is missing from the pip package, as can be seen when opening the zip file at https://pypi.python.org/pypi/panflute.

This causes the installation to fail with this error
```
Collecting panflute
  Downloading panflute-1.0.1.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\fred~1.sun\appdata\local\temp\pip-build-8ombhn\panflute\setup.py", line 15, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "C:\Anaconda2\lib\codecs.py", line 896, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: 'c:\\users\\fred~1.sun\\appdata\\local\\temp\\pip-build-8ombhn\\panflute\\README.md'
----------------------------------------
```

**Comment by sergiocorreia** [comment]
Thanks. I tried it initially on my conputer and it worked fine. Do you know if I should change something in setup.py? Its set to use the readme.md (instead of as a RST file)

**Comment by sergiocorreia** [comment]
Ok I think its because it's missing a manifest file, as discussed here:

https://github.com/FirefighterBlu3/python-pam/commit/294de6307bab380ba75c01a588926b727b372db3

I don't have access to a computer right now but will pull a fix today or tomorrow

**Comment by sergiocorreia** [comment]
It should work now, let me know if you find any problem (tested it only on my local computer)

**Comment by fredizzimo** [comment]
Thanks, it works now :+1:
