### ISSUE TITLE
TravisCI using older versions of code

### ISSUE THREAD

**Issue by sergiocorreia** [sergiocorreia/panflute#41]
Hi  @ickc 

For some reason the TravisCI builds keep failing, and when I inspect the results it show that its failing on some parts of the code that I have already fixed/removed , as if it is using a stale version of panflute

EG: [here](https://travis-ci.org/sergiocorreia/panflute/jobs/186163911#L1483) it uses the stringify function within autofilters.py ,but the latest builds have [no use](https://github.com/sergiocorreia/panflute/blob/master/panflute/autofilter.py) of that function within the autofilter module

Any ideas of what might be going on?

**Comment by sergiocorreia** [comment]
update: it's somehow working now. Not sure if cleaning the cache helped or what..

**Comment by sergiocorreia** [comment]
Thanks!

**Comment by ickc** [comment]
It was kind of stupid: last time when I test travis to pasteurize, I changed the install method to pip, trying to make sure the whole process would install correctly. But then since the pip is cached, it probably is still using the old copy. That explains why it works when you clear the cached.
