### ISSUE TITLE
panflute errors on python 2.7.12

### ISSUE THREAD

**Issue by vanosg** [sergiocorreia/panflute#43]
Hi! First, let me say how useful this has been, thank you very much for putting this together!

On an Ubuntu 16.04.1 machine running python 2.7.12 and pip 9.0.1, I ran:

```
$ sudo -H pip install panflute
Collecting panflute
  Downloading panflute-1.9.2.tar.gz
Requirement already satisfied: pyyaml in /usr/local/lib/python2.7/dist-packages (from panflute)
Requirement already satisfied: future in /usr/local/lib/python2.7/dist-packages (from panflute)
Requirement already satisfied: shutilwhich in /usr/local/lib/python2.7/dist-packages (from panflute)
Building wheels for collected packages: panflute
  Running setup.py bdist_wheel for panflute ... done
  Stored in directory: /root/.cache/pip/wheels/d1/f0/ac/8313c959de9b43243cd3c9a5e5296bd4369bacbc7f40d7b7e6
Successfully built panflute
Installing collected packages: panflute
Successfully installed panflute-1.9.2
```
Note, this was not the GH address you mention in your documentation, it was the pip record you said should work with python 2.7. 

Perhaps the easiest use case error I can provide is copy/pasting directly from your tutorial:
```
>>> e1 = Emph(Str('Hello'), Space, Str('world!'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/panflute/elements.py", line 695, in __init__
    self.text = check_type(text, str)
  File "/usr/local/lib/python2.7/dist-packages/panflute/utils.py", line 29, in check_type
    raise TypeError(msg)
TypeError: received str but expected <class 'future.types.newstr.newstr'>
```
Trying this same command on python 3.6.0, it works fine:
```
>>> e1 = Emph(Str('Hello'), Space, Str('world!'))
>>> 
```

Is it possible that panflute has't been fully ported to 2.7? Did I do something wrong on my install? Any help you can offer would bemuch appreciated, thank you!

**Comment by sergiocorreia** [comment]
Yes, the 2.7 version is very recent!

I don't see anything obvious with the panflute code; to port to py2 it uses `python-future` which might have a bug according to this (slightly older) issues:

https://github.com/PythonCharmers/python-future/issues/170
https://github.com/open-research/sumatra/pull/299

To dig deeper:

panflute does sanity checks all over the place with stuff like `assert isinstance(title, str)`. It seems that the futures module converts this to `assert isinstance(title, futures.types.newstr.newstr)` which fails. This is ok, but the problem is that title should have been converted somewhere to the newstr type.

I'm not sure what's the best fix, but possibly one of the two suggested here:

http://stackoverflow.com/questions/11301138/how-to-check-if-variable-is-string-with-python-2-and-3-compatibility

(i) use basestring, or ii) depend on the six module and use string_types)

**Comment by vanosg** [comment]
I wish I could help! As a beginner-to-intermediate skill python user- do I have any recourse for my modifying my own code to get it to work, or do I need to wait for a panflute update to address this? Thanks again for that quick response!

**Comment by kdheepak** [comment]
Can you try passing in `u'Hello'` instead of `'Hello'`? I'm curious to know
if that will work. I currently don't have Py2 instead on my machine but I
could check some time later.

On Dec 29, 2016 5:11 PM, "Geo" <notifications@github.com> wrote:

I wish I could help! As a beginner-to-intermediate skill python user- do I
have any recourse for my modifying my own code to get it to work, or do I
need to wait for a panflute update to address this? Thanks again for that
quick response!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sergiocorreia/panflute/issues/43#issuecomment-269713498>,
or mute the thread

**Comment by vanosg** [comment]
That worked, for that use case! I don't have the code handy to test more extensively, but maybe you can help me craft an additional test? And pardon me as I'm trying to learn how to use panflute at the same time, so maybe this isn't even right- This is my code, where I'm trying to remove all Strong tags from what pandoc is parsing:
```
def action(elem, doc):
        if isinstance(elem, Para):
                debug(elem)
                elem.walk(makefoo)

def makefoo(elem, doc):
        if isinstance(elem, Strong):
                return Str(elem)
```
So first, I'm sure there's an easier way to do this (And not even sure it will work, as I'm just learning). How would I convert that incoming data to make it work as you did above?

Thank you very much for your help, I'll continue to do more with this later tonight.

**Comment by sergiocorreia** [comment]
If the  basestring fix work I could try pushing it tonight (and given @kdhwepak 's comment and your results, it will probably work).

About your filter: do you want to remove the element, or just replace the bold text with a normal text?

**Comment by vanosg** [comment]
I want to remove just the Strong element, but keep the text 

(Use case: I have .rst files from which  I generate HTML (via sphinx) and plaintext files (via pandoc). The HTML looks good as generated with the ** text, but I don't want pandoc to render the ** text as all caps like it does, so I think by removing the Strong tag I will get the regular text that I want). I'm providing way too much info in the likely case that I'm doing this the hard way :)  Thanks again!

**Comment by sergiocorreia** [comment]
BTW, just submitted a commit that *might* fix this (not entirely sure as I don't have py2 on my laptop). Let me know if it works (or if the error is the same)

**Comment by vanosg** [comment]
Perhaps a step backwards...
```
>>> from panflute import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/panflute/__init__.py", line 9, in <module>
    from .containers import ListContainer, DictContainer
  File "/usr/local/lib/python2.7/dist-packages/panflute/containers.py", line 41
    def __init__(self, *args, oktypes=object, parent=None):
                                    ^
SyntaxError: invalid syntax
```

**Comment by sergiocorreia** [comment]
I'm almost sure you are running the python-3-exclusive version. Can you try uninstalling and installing it again, from pip (not from github).

Also, this filter is what you want:
https://github.com/sergiocorreia/panflute-filters/blob/master/filters/remove-strong.py

(It used to be hard to remove an element, but a PR from an user made it quite easy (so if we return a list of elements, panflute just inserts all the elements on the list).

**Comment by vanosg** [comment]
Yes, that was from git- when I tried updating from pip, it said there was nothing new to install (still 1.9.2)- I just tried again, it appears to have now updated. Let's see...
```
Successfully installed panflute-1.9.3
```
and
```
e1 = Emph(Str('Hello'), Space, Str('world!'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/panflute/elements.py", line 698, in __init__
    self.text = check_type(text, unicode if py2 else str)
  File "/usr/local/lib/python2.7/dist-packages/panflute/utils.py", line 29, in check_type
    raise TypeError(msg)
TypeError: received str but expected <type 'unicode'>
```

**Comment by kdheepak** [comment]
The only way to install the Py2 version I believe is from pip. Since that's
where the pasteurized version is pushed. If Sergio tagged the commit it
should update via Travis automatically in a bit. I'm still on my mobile, so
I'm unfortunately not going to be much help.

**Comment by sergiocorreia** [comment]
I replaced `unicode` with `basestring`, that should make it work. Still no Py2 on my side so can't test it

**Comment by vanosg** [comment]
That fixes that specific error, thank you! And thank you for the remove-strong code as well, that is functional as well. What a great job on this fix! Good luck with this project, it is showing so much promise already
