### ISSUE TITLE
get_metadata throws  AssertionError : assert isinstance(key, str)

### ISSUE THREAD

**Issue by daamien** [sergiocorreia/panflute#47]
Hello, 

Thanks for this piece of software, it's pretty cool but  I'm struggling with the metadata function :

```python
from panflute import *
meta = {'author': MetaString('John Doe')}
content = [Header(Str('Title')), Para(Str('Hello!'))]
doc = Doc(*content, metadata=meta, format='pdf')
a=doc.get_metadata('author')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/panflute/tools.py", line 239, in _get_metadata
    assert isinstance(key, str)
AssertionError
```

Am I doing something wrong ?

**Comment by sergiocorreia** [comment]
This is probably a Python2-related  bug; will try to push a bug fix later

**Comment by sergiocorreia** [comment]
Latest commit is passing but I don't have a py2 machine right now to test this personally. Let me know if the bug is still present on the latest version.

Note: don't install the github version, as only versions from pypi support py2

**Comment by daamien** [comment]
FIXED 

Bravo :-)
