### ISSUE TITLE
PDF link in README.md is broken

### ISSUE THREAD

**Issue by kdheepak** [sergiocorreia/panflute#48]
[http://scorreia.com/software/panflute/Panflute.pdf](http://scorreia.com/software/panflute/Panflute.pdf)

**Comment by sergiocorreia** [comment]
That PDF file is quite tricky to generate (sphinx, compile latex, etc.), so I'll probably delete the link to avoid myself the trouble (unless there's anyone out there that actively uses the PDF?)

**Comment by kdheepak** [comment]
I'm for it. If anyone feels strongly about it we can reopen this issue.
