### ISSUE TITLE
plantuml example does not work

### ISSUE THREAD

**Issue by didibus** [sergiocorreia/panflute#64]
The plantuml example seems to be missing a lot of code. It uses variables that were never initialized for example, it uses filename, but it is never defined or assigned any value.

**Comment by sergiocorreia** [comment]
That example is probably not a good one, as I never tested it (didn't got the required JAR files and so on).

If you have a MWE and/or a link to the required files, I can finish porting it (it's based of an example on jmg's pandocfilters). Else, I can also remove it to prevent confusion.

**Comment by didibus** [comment]
Maybe best the remove it. It confused me for some time, probably because my python is not that great, so I kept thinking maybe there's things I don't understand.
