### ISSUE TITLE
Encoding Problem with French caracters in headers

### ISSUE THREAD

**Issue by daamien** [sergiocorreia/panflute#65]
Hi !

Thanks for this software. It's quite useful.

I think I found an encoding problem when the markdown source has headers with French caracters

I'm using this filter as an example
https://github.com/sergiocorreia/panflute/blob/master/examples/panflute/headers.py

The following works fine:
`pandoc --filter /tmp/headers.py  tests/english_title.md -o _build/5011.pdf`

with `tests/english_title.md` contains just this line :

```
# Normal Title
```

Now let's create a file called `tests/english_title.md` with 1 line:

```
# Titre en français avec plein de caractères bizarres ïéèàù
```

And let's run;
`pandoc --filter /tmp/headers.py  tests/french_title.md -o _build/5011.pdf`

Here comes trouble:

```
Traceback (most recent call last):
  File "/tmp/headers.py", line 17, in <module>
    main()
  File "/tmp/headers.py", line 13, in main
    return run_filter(increase_header_level, doc=doc)
  File "/usr/local/lib/python2.7/dist-packages/panflute/io.py", line 265, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/panflute/io.py", line 238, in run_filters
    doc = load(input_stream=input_stream)
  File "/usr/local/lib/python2.7/dist-packages/panflute/io.py", line 61, in load
    doc = json.load(input_stream, object_pairs_hook=from_json)
  File "/usr/lib/python2.7/json/__init__.py", line 286, in load
    return loads(fp.read(),
  File "/usr/lib/python2.7/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 47: ordinal not in range(128)
pandoc: Error running filter /tmp/headers.py
Filter returned error status 1
```

**Comment by sergiocorreia** [comment]
Hi Daamien,

Do you have access to py3? If so, could you try running it there to see if the issue persists?

The py2 version of Panflute *should* work, but that version is mostly built automatically with 3to2, so I'm not that surprised to see unicode issues.  In this specific case, the bug might be related with json.load missing an encoding option, but [as per the py2 manual](https://docs.python.org/2/library/json.html#json.load), json.load should have defaulted to utf-8 encoding and not ascii encoding. Since I don't have py2 installed on my laptop, I'm not sure if I can fix the issue (unless it also occurs on py3), but if you or another user submit a PR I can merge it for sure.

Best,
Sergio

**Comment by daamien** [comment]
ok I'll give it a try....

If I install a python3 on  machine with python2, how can I force pandoc to use python3 to interpret the filter ?

**Comment by sergiocorreia** [comment]
Yes, there are several ways for this depending on your system:

On *nix, you could use shebang lines: https://docs.python.org/3/using/windows.html#shebang-lines

On windows, I think there is a new utility called "py" that comes with the latest version of py2 or py3, which also allow shebangs.

**Comment by daamien** [comment]
Sorry to bother with that but pandoc seems to use python2 only....

The shebang is there
```
cat /tmp/headers.py 
#!/usr/bin/python3
````
panflute is installed with pip3

```
# pip3 install panflute
Requirement already satisfied (use --upgrade to upgrade): panflute in /usr/local/lib/python3.4/dist-packages
Cleaning up...
```
But pandoc still fails like this

```
pandoc tests/french_title.md --filter /tmp/headers.py -o test.pdf
Traceback (most recent call last):
  File "/tmp/headers.py", line 3, in <module>
    from panflute import run_filter, Header
ImportError: No module named panflute
pandoc: Error running filter /tmp/headers.py
Filter returned error status 1
```

In the python3 console, i can load panflute :

~~~
# python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import panflute
>>>
~~~

**Comment by daamien** [comment]
ok I solved the problem : If the filter is not executable, the shebang is ignored  and the default python env is used:
https://github.com/jgm/pandoc/issues/3174

A simple ```chmod a+x /tmp/headers.py``` fixed issue.

Indeed the filters works fine with a python3 environment...

You should problably write somewhere in the documentation that Python2 is not well supported.

Thanks for your time and for this software !

**Comment by sergiocorreia** [comment]
Great to hear that! And yes, I agree about python 2 support (which as of now, mostly depends on external commiters)

**Comment by K4zuki** [comment]
I faced Very similar situation(Japanese) :)

**Comment by sergiocorreia** [comment]
Hi Kazuki,

Does it work on py3?

**Comment by K4zuki** [comment]
no worries 
no problem it worked with py3
I was also using py2

**Comment by damiendr** [comment]
There are similar issues with autofilters and unicode literals in the Python source, which can be traced there:
https://github.com/sergiocorreia/panflute/blob/b9bc64c4ee557bc6daa8fb55e24c169f2a3a51ed/panflute/autofilter.py#L83-L85

I fixed it with `open(fn, encoding="utf-8")`, but I'm not sure if that's the best solution (this ignores any encoding headers in the python source)

**Comment by sergiocorreia** [comment]
> I fixed it with open(fn, encoding="utf-8"), but I'm not sure if that's the best solution (this ignores any encoding headers in the python source)

@damiendr I wouldn't mind adding it, but one question: is this a py2 or py3 issue?

**Comment by damiendr** [comment]
This is with Python 3.

**Comment by reagle** [comment]
Making the python filters executable solved my problem too, that should be added to the installation documentation.
