### ISSUE TITLE
RawBlock RAW_FORMATS too restrictive

### ISSUE THREAD

**Issue by parchd-1** [sergiocorreia/panflute#67]
Currently this line is present in elements.py

```python
RAW_FORMATS = {'html', 'tex', 'latex', 'context'}
```
Which means a lot of filters are not possible for other output formats. For example, the filter I am currently writing is for docx output and uses raw xml.

For my present situation, changing the line to

```python
RAW_FORMATS = {'html', 'tex', 'latex', 'context', 'openxml'}
```
would be sufficient, but I also suggest that this check should not exist at all.

**Comment by sergiocorreia** [comment]
I would keep the check; else we could see filters failing silently due to typos.

But I can add this or other formats for sure.

**Comment by parchd-1** [comment]
Thanks for making the change so quickly. That should cover the majority of cases.

I see your point about things failing because of typos.
