### ISSUE TITLE
Improve path discovery of scripts installed through pip

### ISSUE THREAD

**Issue by sergiocorreia** [sergiocorreia/panflute#69]
When e.g. `pantable` gets installed, `pantable.exe` is placed within $PATH, but panflute can't find it

However, panflute could just do `import pantable; doc = pantable.main(doc)`.

On Python 3.4+, we can check this with:

```python
import importlib
spam_spec = importlib.util.find_spec("spam")
found = spam_spec is not None
```

(or we could just `try` to import it..)

**Comment by ickc** [comment]
Why not give it a `try`? ;)

**Comment by sergiocorreia** [comment]
`try` is probably simpler and more pythonic, agreed.

Would like to set up some hours to update misc. stuff in the next week(s) so let me know if there are other things we should do.
