### ISSUE TITLE
Wrapping Link with Div

### ISSUE THREAD

**Issue by HaoZeke** [sergiocorreia/panflute#73]
Hi, I've attempted to iterate over Links and tried Div.content.extend(Link) but I can't seem to get a link wrapped in a div outputted....

Any ideas?

**Comment by sergiocorreia** [comment]
There are roughly two types of Pandoc elements: block elements (paragraphs, lists, etc.) and inline elements (strings, spaces, bold text, etc.).

A Div is a block element that can [only contain other block elements](http://scorreia.com/software/panflute/code.html#panflute.elements.Div) (see the part that says "args (Block) – contents of the div")).

On the other hand, a link is an inline element, so it cannot be contained directly inside a div. What you need to do is put the link in a block that can contain inlines (Para, Plain, etc.) and put that in a Div.

For instance:

```python
import panflute as pf
div = pf.Div()
link = pf.Link(pf.Str('SomeText'), url='http://www.example.com')
# This fails:
div.content.append(link)
# This works:
div.content.append(pf.Plain(link))
```

**Comment by HaoZeke** [comment]
Thanks! I was also wondering if there was a canonical way to insert a list of elements...

replace_keyword doesn't work for lists (NotImplementedError)

I noted that the documentation suggests wrapping them in another div,

ie.

```bash
div = Div(*IamLegion)
doc = doc.replace_keyword('$spooky', div)
```

However that's throwing my layout off... is there a way to remove the empty enclosing div?

**Comment by sergiocorreia** [comment]
Would it work if you use a span instead of a div? They are kinda the same, except that Span is an inline that contains inlines and Div is a block that contains blocks.

**Comment by HaoZeke** [comment]
I shall name the div and unstyle it purposefully in my css I guess...

```bash
def prepare(doc):
    doc.hLinks = []
    doc.depth = int(doc.get_metadata('toc-depth', default=1))


def action(elem, doc):
    if isinstance(elem, Header) and elem.level <= doc.depth:
        plain = stringify(elem)
        item = Link(*elem.content,url="#"+stringify(elem))
        doc.hLinks.append(item)
        return []


def finalize(doc):
    div = []
    for x in range(len(doc.hLinks)):
       div.append(Div(classes=['navItem']).content.append(Plain(doc.hLinks[x])))
    divR = Div(*div, classes=['noLove'])
    doc = doc.replace_keyword('$hLinks', divR)
    del doc.hLinks, doc.depth, div
```

The code above errors out with TypeError: received NoneType but expected <class 'panflute.base.Block'>
, if I try *doc.hLinks I get the same error and with plain do.hLinks I get a list error...

Any ideas?

**Comment by sergiocorreia** [comment]
BTW you don't need the `del` statement..  the objects will automatically be deleted at the end.

Also, the `for x in range..` iteration might be more Pythonic if you just write it as a list comprehension:

```python
divs = [Div(Plain(x), classes=['navItem']) for x in doc.hLinks]
```
This also helps in solving the error, which is that you are creating Div() without any content, and then appending to it ("received NoneType"). Instead, here you create Div with Plain(x) as content directly.

**Comment by HaoZeke** [comment]
That worked perfectly! Thanks a ton :D (I'm new to python actually)
