### ISSUE TITLE
some reference code for the help web page seems out of date

### ISSUE THREAD

**Issue by K4zuki** [sergiocorreia/panflute#75]
It seems following page and/or its reference code in the site seems to be out of date:

- <http://scorreia.com/software/panflute/_modules/panflute/elements.htm>

The page(code) says `RAW_FORMATS = {'html', 'tex', 'latex'}` while in recent code this variable has
`openxml` etc. also. 

- [line 1313~](https://github.com/sergiocorreia/panflute/blob/b9bc64c4ee557bc6daa8fb55e24c169f2a3a51ed/panflute/elements.py#L1313)

**Comment by sergiocorreia** [comment]
Thanks, I'll update it!
