### ISSUE TITLE
Add testing framework

### ISSUE THREAD

**Issue by kdheepak** [sergiocorreia/panflute#8]

**Comment by sergiocorreia** [comment]
Agreed. We need a few things:

1. Something like [Travis](https://www.quora.com/What-is-the-difference-between-Bamboo-CircleCI-CIsimple-Ship-io-Codeship-Jenkins-Hudson-Semaphoreapp-Shippable-Solano-CI-TravisCI-and-Wercker). 2. More markdown files so we can check if dump(load()) is an identity function.
3. An example filter that uses `.next` and all the navigation methods, but at the end returns the same value (for simplicity)
4. A very *very* large markdown file so we can benchmark [performance](https://github.com/aaren/pandoc-reference-filter/issues/20#issuecomment-221071039)

**Comment by sergiocorreia** [comment]
About finding large markdown files, one option is to search github for [existing files](https://github.com/search?utf8=%E2%9C%93&q=title+language%3AMarkdown++size%3A%3E100000&type=Code&ref=searchresults)

**Comment by sergiocorreia** [comment]
The test suite is not quite comprehensive but should be enough for now, so I'm closing this
