### ISSUE TITLE
autorun filters with dependencies?

### ISSUE THREAD

**Issue by ekiim** [sergiocorreia/panflute#80]
Is there a way to implement autorun filters with dependencies?

The use case, is that I have a set of filters, in separate files, but they depend on a another module (I did), that contains a series of utility functions?

**Comment by lionawurscht** [comment]
Not sure, whether this is what you meant but I wrote something to resolve dependencies between filters for myself: https://gist.github.com/lionawurscht/975f8201fea1caf30699cea52a44112b

I use it like this (didn't actually run that code, but you should get the idea.):
```python
#!/usr/bin/env python
import panflute as pf

from . import other_filters

@make_dependent(
    other_filters.delete_comments  # delete_comments would also habe to be decorated with @make_dependent
)
def process_headers(elem, doc):
    if isinstance(elem, pf.MetaMap):
        for key, value in elem.content.items():
            string = pf.stringify(value).strip()

            t_f = string == 'true'
            elem[key] = pf.MetaBool(t_f)

@make_dependent(
    other_filters.prepare  # other_filters.prepare was also decorated ...
)
def prepare(doc):
    pass


if __name__ == '__main__':
    pf.run_filters(
        utils.reduce_dependencies(  # Tries to sort all the functions according to their dependencies
            process_headers,
        ),
        prepare=prepare.to_function(),
        doc=None,
    )

```

Again, I wrote that for myself and I only program as a sort of hobby for my own pleasure ;)

**Comment by ekiim** [comment]
I've submitted a pull request, where, I added the feature, turns out, that the section of panflute that makes the application of the filters in sequence, basically It's a for loop, doing an `eval` on the source code of each filter file.

What I did,  a context manager, that puts in the path, the `/dir/to/filters` directory, allowing to do an `import` of the filter and that way you can import files from the directory containing the filters. 

The request has no extra dependencies, just one class I added and rewrote the filter evaluation part. 

you could check it out and comment on it, If interested
