### ISSUE TITLE
move figures at the end of docx

### ISSUE THREAD

**Issue by myutkin** [sergiocorreia/panflute#94]
Hi there,

I am trying to write a filter to move all figures with captions at the end of the document. Much alike the filter for tables (https://github.com/sergiocorreia/panflute-filters/blob/master/filters/table.py). However, there seems to be a big difference between these two. I can move the image, but not its caption. How should I approach this problem?

P.S.: The solution with codeblock (https://github.com/sergiocorreia/panflute-filters/blob/master/filters/figure.py) does not work for me.

**Comment by sergiocorreia** [comment]
Sorry for missing your issue earlier. Can you provide a MWE so I can see what approach you did?

**Comment by myutkin** [comment]
Hi! Sorry for later reply.

Here is my "md" file

`---
title: Example Title
link-citations: true
eqnPrefix: "Eq."
figPrefix: "Figure"
tblPrefix: "Table"
numbersections: true
linkReferences: true
tableEqns: false
nameInLink: true
chapters: True
chaptersDepth: 1
chapDelim: ""
---

Section1 {-}
============

However venture pursuit he am mr cordial. Forming musical am hearing studied be luckily. Ourselves for determine attending how led gentleman sincerity. Valley afford uneasy joy she thrown though bed set. In me forming general prudent on country carried. Behaved an or suppose justice. Seemed whence how son rather easily and change missed. Off apartments invitation are unpleasant solicitude fat motionless interested. Hardly suffer wisdom wishes valley as an. As friendship advantages resolution it alteration stimulated he or increasing [@fig:lab1].

![Some caption1.](figure1.png){#fig:lab1}

Was certainty remaining engrossed applauded sir how discovery. Settled opinion how enjoyed greater joy adapted too shy. Now properly surprise expenses interest nor replying she she. Bore tall nay many many time yet less. Doubtful for answered one fat indulged margaret sir shutters together. Ladies so in wholly around whence in at. Warmth he up giving oppose if. Impossible is dissimilar entreaties oh on terminated. Earnest studied article country ten respect showing had. But required offering him elegance son improved informed [@fig:lab2].

![Some caption2.](figure2.png){#fig:lab2}

Section2 {-}
===========

Abilities forfeited situation extremely my to he resembled. Old had conviction discretion understood put principles you. Match means keeps round one her quick. She forming two comfort invited. Yet she income effect edward. Entire desire way design few. Mrs sentiments led solicitude estimating friendship fat. Meant those event is weeks state it to or. Boy but has folly charm there its. Its fact ten spot drew.

$figures`

I use the following code to move figures to the end of the file, but figure captions disappear:

`#!C:/python36/python.exe
"""
Move tables to where the string $tables is.
"""

from panflute import *


def prepare(doc):
    doc.backmatter = []


def action(elem, doc):
    if isinstance(elem, Image):
        doc.backmatter.append(elem)
        return []


def finalize(doc):
    div = Image(*doc.backmatter)
    doc = doc.replace_keyword('$figures', div)


def main(doc=None):
    return run_filter(action, prepare, finalize, doc=doc)


if __name__ == '__main__':
    main()`

The code for figure relocation based on ~~~ tags could have worked for me, but I need to move over ten figures and thus would need to change them into appropriate format, which defeats the purpose of the whole exercise. 

Appreciate your help!

P.S.: This code is run on windows with pandoc to generate docx. However, the result is pretty much the same on linux.
