### ISSUE TITLE
builtin2meta fails with str type

### ISSUE THREAD

**Issue by chrisjsewell** [sergiocorreia/panflute#97]
Because in python 2, you redirect str -> basestring, this [line fails](
https://github.com/sergiocorreia/panflute/blob/65c2d570c26a190deb600cab5e2ad8a828a3302e/panflute/elements.py#L1485):

```python
TypeError: The basestring type cannot be instantiated
```

Obviously, python 2.7 is on its last legs, so not a massive deal. 
But general practice is to use [six.string_types](https://pythonhosted.org/six/#six.string_types) for checking string instances.

**Comment by chrisjsewell** [comment]
Actually, it seems to be an issue in python 3 as well

```python
>>> builtin2meta("a")
"a"
```

Maybe it would be best to also raise an error if the conversion fails:

```python
from six import string_types

def builtin2meta(val):
    if isinstance(val, bool):
        return pf.MetaBool(val)
    elif isinstance(val, (float, int)):
        return pf.MetaString(str(val))
    elif isinstance(val, string_types):
        return pf.MetaString(val)
    elif isinstance(val, list):
        return pf.MetaList(*[builtin2meta(x) for x in val])
    elif isinstance(val, dict):
        return pf.MetaMap(*[(k, builtin2meta(v)) for k, v in val.items()])
    elif isinstance(val, pf.Block):
        return pf.MetaBlocks(val)
    elif isinstance(val, pf.Inline):
        return pf.MetaInlines(val)
    elif isinstance(val, (pf.MetaBool, pf.MetaString, pf.MetaValue,
                          pf.MetaList, pf.MetaMap, pf.MetaBlocks,
                          pf.MetaInlines)):
        return val
    
    raise TypeError("unknown type: {} (type: {})".format(val, type(val)))
```

**Comment by sergiocorreia** [comment]
Thanks for the report. I've been thinking for a while about the py2 issue, as it's creating quite a few issues that six does not entirely support (I think there are a couple *hundred* open issues on the six repo..).

Given that py2 has 10 months and 17 days of life left, maybe we should scrap the py2-related code to ease development?

**Comment by ickc** [comment]
> Given that py2 has 10 months and 17 days of life left, maybe we should scrap the py2-related code to ease development?

If it becomes too difficult to fix something because it has to cover Python 2 then yes. In the README you can state for Python 2 use below a certain version only (I think if the setup.py is setup correctly it is automatic.)

I also faced some problems supporting Python 2. Particularly currently it is difficult to package panflute in conda. (pandocfilter is in conda but panflute is only in PyPI.)

**Comment by sergiocorreia** [comment]
py2 is now unsupported
