### ISSUE TITLE
convert_text throws TypeError when converting Inline elements from panflute to markdown

### ISSUE THREAD

**Issue by daniel-keller** [sergiocorreia/panflute#99]
I receive a TypeError when implementing a filter which uses convert_text to convert the bold word **test** from panflute to markdown. I have replicated the error when converting the `Span`, `Emph`, `Code`, and `RawInline`. The error is not thrown when converting `Div` or `RawBlock`. Wrapping inline elements in `Div` also produces the error.

I'm using Python 2.7 and Pandoc 2.3.1

Simplified filter:
> from panflute import *
> 
> def action(elem, doc):
>   comment = convert_text(Strong(Str("test")), input_format='panflute', output_format='markdown')
> 
> def main(doc=None):
>   return run_filter(action, doc=doc)
> 
> if __name__ == '__main__':
>   main()

Full error:
> Traceback (most recent call last):
>   File "tmp_filter.py", line 11, in <module>
>     main()
>   File "tmp_filter.py", line 8, in main
>     return run_filter(action, doc=doc)
>   File "/usr/local/lib/python2.7/site-packages/panflute/io.py", line 266, in run_filter
>     return run_filters([action], *args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/panflute/io.py", line 247, in run_filters
>     doc = doc.walk(action, doc)
>   File "/usr/local/lib/python2.7/site-packages/panflute/base.py", line 272, in walk
>     ans = obj.walk(action, doc)
>   File "/usr/local/lib/python2.7/site-packages/panflute/base.py", line 290, in walk
>     altered = action(self, doc)
>   File "tmp_filter.py", line 4, in action
>     comment = convert_text(Strong(Str("test")), input_format='panflute', output_format='markdown')
>   File "/usr/local/lib/python2.7/site-packages/panflute/tools.py", line 402, in convert_text
>     text = Doc(*text, api_version=api_version)
>   File "/usr/local/lib/python2.7/site-packages/panflute/elements.py", line 66, in __init__
>     self._set_content(args, Block)
>   File "/usr/local/lib/python2.7/site-packages/panflute/base.py", line 135, in _set_content
>     self._content = ListContainer(*value, oktypes=oktypes, parent=self)
>   File "/usr/local/lib/python2.7/site-packages/panflute/containers.py", line 65, in __init__
>     self.extend(args)  # self.oktypes must be set first
>   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_abcoll.py", line 675, in extend
>     self.append(v)
>   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_abcoll.py", line 664, in append
>     self.insert(len(self), value)
>   File "/usr/local/lib/python2.7/site-packages/panflute/containers.py", line 91, in insert
>     v = check_type(v, self.oktypes)
>   File "/usr/local/lib/python2.7/site-packages/panflute/utils.py", line 30, in check_type
>     raise TypeError(msg)
> TypeError: received Strong but expected <class 'panflute.base.Block'>
> Error running filter tmp_filter.py:
> Filter returned error status 1

**Comment by daniel-keller** [comment]
It looks like convert_text tries to wrap any panflute input in a Doc element but the Doc element constructor can only accept Block elements (and those that extend Block elements). A good work around is to first wrap your Inline element in a Para or other Block element. Maybe convert_text could do this automatically? That might create unexpected results in some cases though. If there is no good solution for convert_text to manage this use case it would be good to update the documentation to accordingly.

**Comment by sergiocorreia** [comment]
Partly fixed by #104
